# SPDX-FileCopyrightText: 2023 Simon Dalvai <info@simondalvai.org>

# SPDX-License-Identifier: CC0-1.0

name: itch.io upload

on:
  push:
    paths:
      - "version"
      - ".github/workflows/upload-itchio.yml"

env:
  WORKING_DIRECTORY: app

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Delete iOS icons
        run: rm -rf $WORKING_DIRECTORY/AppIcons

      - name: Create export directory
        run: mkdir html5

      - name: Create export_presets.cfg
        run: cp $WORKING_DIRECTORY/export_presets.html.example $WORKING_DIRECTORY/export_presets.cfg

      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1.0.2
        with:
          working-directory: $WORKING_DIRECTORY
          godot-version: 4.3
          godot-channel: stable

      - name: Upload to itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: html5
          api-key: ${{ secrets.ITCHIO_API_KEY }}
          user: simondalvai
          game: condor
          channel: html5

